### ISSUE TITLE
A quick review

### ISSUE THREAD

**Issue by vxgmichel** [python-trio/sniffio#1]
## String vs module

The library is currently identified using a string:
```python
library = current_async_library()
if library == "trio": ...
```
What about using the module itself?
```python
import trio
[...]
library = current_async_library()
if library is trio: ...
```

## Support for older curio/trio releases

Current  or older curio/trio versions won't be detected. 

Maybe have a fallback to detect them (e.g using `trio.hazmat.current_task()`)?

If not, it'd be good to list the compatible versions of the different libraries in the documentation.

## Set context var after sniffing when possible

If the current loop implements PEP 567, the context var can be set after sniffing to avoid performing the detection several times in the same task. 

PEP 567 support might be complicated to detect though.

**Comment by smurfix** [comment]
I don't like using the module itself because the user of the interface would need to import Trio before being able to check whether Trio is used. It isn't? oh, you just wasted a second loading heaps of Python code you don't need, my bad.

IMHO we should go with the "return an object with a `name` attribute and a couple of to-be-decided useful methods" (like `XXX.sleep) idea.

**Comment by njsmith** [comment]
> "return an object with a `name` attribute and a couple of to-be-decided useful methods" (like `XXX.sleep`) idea.

I think I want to see what the to-be-decided useful methods are before forming an opinion :-).

If it's literally just `sleep` and `current_time`, then ... meh, I don't think it's worth it.

And, I don't think this library should be opinionated, because it's a piece of core functionality that everyone *has* to use. Any methods we put in here become part of the API that every async library has to implement in order to be sniffable. So opinionated stuff should go into downstream libraries like `multio`, so then people can argue about them and choose their favorite.

So my question is... *is* there actually anything beyond `sleep` and `current_time` that everyone agrees on?

**Comment by njsmith** [comment]
Actually on further thought... Even `sleep` and `current_time` aren't universal, because on twisted, properly written code that uses these operations is supposed to accept an explicit [`IReactorTime`](https://twistedmatrix.com/documents/current/api/twisted.internet.interfaces.IReactorTime.html) object, to allow something like trio's clock overriding but on a fine-grained call-by-call basis.

**Comment by smurfix** [comment]
On 30.07.2018 19:25, Nathaniel J. Smith wrote:
>
> Actually on further thought... Even |sleep| and |current_time| aren't
> universal, because on twisted, properly written code that uses these
> operations is supposed to accept an explicit |IReactorTime|
> <https://twistedmatrix.com/documents/current/api/twisted.internet.interfaces.IReactorTime.html>
> object, to allow something like trio's clock overriding but on a
> fine-grained call-by-call basis.
>
Owch. Thanks, I wasn't aware of that.

So, my remaining argument for something more structured is trio-asyncio
– i.e., you're currently in mode A but might want to figure out whether
it's possible to switch to mode B.

In fact, a `trio_curio` or `trio_twisted` adapter that works along the
same lines as `trio_asyncio` should certainly be possible. Just don't
try to convince me to implement `trio_gevent` :-P

-- 
-- Matthias Urlichs

**Comment by njsmith** [comment]
@vxgmichel 

> Current or older curio/trio versions won't be detected. Maybe have a fallback to detect them (e.g using `trio.hazmat.current_task()`)?

I actually started implementing this (for trio, I don't know how to do it for curio), but then stopped when I realized how much more complicated it made the CI matrix :-). Esp. because I don't think supporting old trio versions matters that much, since trio is still young enough that you kind of have to upgrade it pretty regularly :-). You're right that documenting it would be helpful, though, so I just did that :-).

> If the current loop implements PEP 567, the context var can be set after sniffing to avoid performing the detection several times in the same task. PEP 567 support might be complicated to detect though.

I guess for asyncio we could set the contextvar if `(3, 7) <= sys.version`?

@smurfix
> So, my remaining argument for something more structured is trio-asyncio – i.e., you're currently in mode A but might want to figure out whether it's possible to switch to mode B.

Not sure I understand how you think sniffio could/should indicate this... like if you're in trio mode then you certainly can use trio-asyncio to switch to asyncio mode, that's what it does :-). But I guess you mean something like detecting whether trio-asyncio has already created a loop that you can use? I'm having trouble visualizing the use case...

**Comment by smurfix** [comment]
> But I guess you mean something like detecting whether trio-asyncio has already created a loop that you can use? I'm having trouble visualizing the use case...

More like, are we running "native" asyncio (if I want to run a Trio task I need to start a new thread) or are we running on top of trio-asyncio (just call `loop.run_trio`). But on second thought I could just check `hasattr(loop, 'run_trio')`, so I'm OK with the simple string reply – and if we ever need something more structured, well, we can always add another entry point.

**Comment by vxgmichel** [comment]
@smurfix 
> I don't like using the module itself because the user of the interface would need to import Trio before being able to check whether Trio is used.

Alright, makes sense!

@njsmith 
> You're right that documenting it would be helpful, though, so I just did that :-)

Great, thanks!

@njsmith 
> I guess for asyncio we could set the contextvar if (3, 7) <= sys.version?

Sounds good!

@smurfix 
> IMHO we should go with the "return an object with a name attribute and a couple of to-be-decided useful methods" (like `XXX.sleep) idea.

I don't really see the point of a more complicated structure. In cases where loop interoperability is needed it [typically goes further than `sleep` and `current_time`](https://github.com/vxgmichel/aiostream/issues/17#issuecomment-403440794), and I assume it'd be quite hard to find an uncontroversial interface for functionalities like `wait` or `gather`.

All my comments have been addressed, feel free to close this issue when needed. 

Thank you both for your efforts :)

**Comment by njsmith** [comment]
Okay, and I added caching for asyncio 3.7+, so I think that's everything! I'll probably release to pypi tomorrow.

**Comment by njsmith** [comment]
https://pypi.org/project/sniffio/

Now we just have to merge https://github.com/python-trio/trio/pull/572 and release a new trio :-)
